# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - tcazr-test-webapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            .
            !venv/

      - name: Register build artifact in ServiceNow
        uses: ServiceNow/servicenow-devops-register-artifact@v3.1.0
        with:
          devops-integration-token: ${{ secrets.SN_DEVOPS_INTEGRATION_TOKEN }}
          instance-url: ${{ secrets.SN_INSTANCE_URL }}
          tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
          job-name: "Register Artifact"
          context-github: ${{ toJSON(github) }}
          artifacts: >-
            [
              {
                "name": "python-app",
                "version": "1.${{ github.run_number }}",
                "semanticVersion": "1.${{ github.run_number }}.0",
                "repositoryName": "${{ github.repository }}",
                "branchName": "${{ github.ref_name }}",
                "commitId": "${{ github.sha }}"
              }
            ]

  ServiceNowDevOpsChange:
    needs: build
    runs-on: ubuntu-latest
    name: ServiceNow DevOps Change (Deployment Gate)

    steps:
      - name: Register deployment gate
        uses: ServiceNow/servicenow-devops-change@v6.1.0
        with:
          devops-integration-token: ${{ secrets.SN_DEVOPS_INTEGRATION_TOKEN }}
          instance-url: ${{ secrets.SN_INSTANCE_URL }}
          tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
          context-github: ${{ toJSON(github) }}
          job-name: ServiceNow DevOps Change
          deployment-gate: >-
            {
              "environment": "prod",
              "jobName": "deploy"
            }
      - name: Get change details after approval
        id: get-change
        uses: ServiceNow/servicenow-devops-get-change@v1.0.0
        with:
          devops-integration-token: ${{ secrets.SN_DEVOPS_INTEGRATION_TOKEN }}
          instance-url: ${{ secrets.SN_INSTANCE_URL }}
          tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
          context-github: ${{ toJSON(github) }}
          job-name: Get Change

      - name: Log change info
        run: |
          echo "Change Request Number: ${{ steps.get-change.outputs.change-request-number }}"
          echo "Change Request URL: ${{ secrets.SN_INSTANCE_URL }}/nav_to.do?uri=change_request.do?sys_id=${{ steps.get-change.outputs.change-request-sys-id }}"

# To override change request fields instead of using record preset
# Add the attributes hash in the deployment gate after jobName, including the attribute and value to override.
# , "attributes": {
#     "short_description": "Hotfix deployment for payment API",
#     "description": "Triggered by GitHub Actions for urgent fix",
#     "assignment_group": "<sys_id of CAB group>",
#     "priority": "2",
#     "implementation_plan": "Deploy hotfix branch and monitor API latency",
#     "backout_plan": "Revert to previous artifact and restore DB snapshot",
#     "test_plan": "Run regression suite and validate payment flow",
#     "category": "Software",
#     "risk": "Medium",
#     "impact": "Medium",
#     "cmdb_ci": "<sys_id of Application Service CI>",
#     "u_environment": "prod"
# }

  deploy:
    needs: ServiceNowDevOpsChange
    runs-on: ubuntu-latest
    environment: prod
    permissions:
      id-token: write
      contents: read

    env:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_OIDC_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZUREAPPSERVICE_TENANTID_5909E22C6034485D950022D0F2447A5F }}
      SERVICE_NOW_API: ${{ secrets.SERVICE_NOW_API }}
      FLASK_SECRET: ${{ secrets.FLASK_SECRET }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_OIDC_CLIENT_ID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5909E22C6034485D950022D0F2447A5F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_51A493B9A49A4035A19E7838BA54461C }}

      - name: Set App Service settings
        uses: azure/cli@v2
        with:
          inlineScript: |
            az webapp config appsettings set \
              --resource-group TCAZR-UKSOUTH-WEBHOSTING-RSG \
              --name tcazr-test-webapp \
              --settings \
                AZURE_CLIENT_ID=${{ secrets.AZURE_OIDC_CLIENT_ID }} \
                AZURE_TENANT_ID=${{ secrets.AZUREAPPSERVICE_TENANTID_5909E22C6034485D950022D0F2447A5F }} \
                FLASK_SECRET=${{ secrets.FLASK_SECRET }} \
                SERVICE_NOW_API=${{ secrets.SERVICE_NOW_API }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'tcazr-test-webapp'
          slot-name: 'Production'

  close-change:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Update (close) change in ServiceNow
        uses: ServiceNow/servicenow-devops-update-change@v1.0.0
        with:
          devops-integration-token: ${{ secrets.SN_DEVOPS_INTEGRATION_TOKEN }}
          instance-url: ${{ secrets.SN_INSTANCE_URL }}
          tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
          context-github: ${{ toJSON(github) }}
          job-name: Close Change
          attributes: >-
            {
              "state": "Closed",
              "close_code": "successful",
              "close_notes": "Deployment completed successfully and validated"
              /* Uncomment to override closure details:
              , "close_code": "successful",
                "close_notes": "Hotfix deployed and verified in production"
              */
            }